version: '3.11.5'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:1134@db:5432/fp_base
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    # ports:
    #   - "5454:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1134
      - POSTGRES_DB=fp_base
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: mamukov2000@mail.ru
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   # volumes:
  #   #   - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  # pgadmin: