"""Ok, lets go back

Revision ID: 8c8fd44eb7d7
Revises: 91ea2217da6c
Create Date: 2023-11-16 09:06:02.850034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8fd44eb7d7'
down_revision: Union[str, None] = '91ea2217da6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
