"""Add books table in db

Revision ID: ccad0351be48
Revises: e237d6c26660
Create Date: 2023-11-16 13:46:42.613880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccad0351be48'
down_revision: Union[str, None] = 'e237d6c26660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('author_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('create_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_change_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], name='author_id'),
    sa.PrimaryKeyConstraint('book_id', name='book_id')
    )
    # ### end Alembic commands ###
